name: build

on: [push, pull_request] 上：[推，拉请求]

jobs:

  build:

    runs-on: ${{ matrix.os }}
运行：${{matrix.os}}

    strategy:

      fail-fast: false

      matrix:

        os: [windows-latest]
操作系统：[windows-最新]

        build_type: [Release]
构建类型：[发布]

        enable_ui: [on]

        include:

          - os: windows-latest
- 操作系统：windows-最新

            build_type: Release
构建类型：发布

            enable_ui: on

    steps:

    - uses: actions/checkout@v3  - 使用：actions/checkout@v3

      with:

        submodules: 'recursive'
子模块：“递归”

    - name: ccache  - 名称：ccache

      uses: hendrikmuhs/ccache-action@v1
使用：hendrikmuhs/ccache-action@v1

      if: runner.os == 'Linux'
如果：runner.os == 'Linux'

      with:

        key: ${{ matrix.os }}-${{ matrix.enable_ui }}
键：${{matrix.os}}-${{matrix.enable_ui}}

    - uses: seanmiddleditch/gha-setup-ninja@master
- 使用：seamiddleditch/gha-setup-ninja@master

    - uses: ilammy/msvc-dev-cmd@v1  - 使用：ilammy/msvc-dev-cmd@v1

      if: runner.os == 'Windows'

    - name: Install Dependencies
- 名称：安装依赖项

      shell: bash

      run: |

        if [[ "${{ runner.os }}" == "Linux" ]] ; then
if [[ "${{ runner.os }}" == "Linux" ]] ;然后

          sudo apt-get update -qq
sudo apt-get 更新-qq

          sudo apt-get install -y \

            libx11-dev libxcursor-dev libxi-dev

        fi

    - name: Generating Makefiles
- 名称：生成 Makefile

      shell: bash

      run: |

        if [[ "${{ runner.os }}" == "Windows" ]] ; then
if [[ "${{ runner.os }}" == "Windows" ]] ;然后

          export enable_ccache=off
导出enable_ccache=关闭

        else

          export enable_ccache=on
导出enable_ccache=on

        fi

        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip
卷曲-L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --输出skia.zip

        7z x skia.zip
7z x 滑雪.zip

        cmake -S . -B build -G Ninja \
cmake -S 。 -B 构建 -G 忍者 \

          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
-DCMAKE_BUILD_TYPE=${{matrix.build_type}}\

          -DENABLE_UI=${{ matrix.enable_ui }} \
-DENABLE_UI=${{matrix.enable_ui}}\

          -DENABLE_CCACHE=$enable_ccache \

          -DLAF_BACKEND=skia \

          -DSKIA_DIR=./skia \

          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \

          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
-DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

    - name: Compiling - 名称：编译

      shell: bash

      run: |

        cd build && ninja
CD 构建 && 忍者

    - uses: actions/upload-artifact@v3
- 使用：actions/upload-artifact@v3

      with:

        name: aseprite

        path: |

          D:/a/aseprite/aseprite/build/bin/data

          D:/a/aseprite/aseprite/build/bin/aseprite.exe
D:/a/aseprite/aseprite/build/bin/aseprite.exe
